sonar.projectKey=banco-java-puro
sonar.projectName=Sistema Bancario Java
sonar.projectVersion=1.0

# Credenciales por defecto
sonar.token=squ_79849bcffa92a78bf85a95f419bb7abfcda6f28c
#sonar.password=Abelardo2509_


# Rutas del proyecto
sonar.sources=src/main
sonar.tests=src/tests
sonar.java.binaries=bin
sonar.coverage.jacoco.xmlReportPaths=reportes/jacoco.xml
